# Generated by Django 2.2 on 2021-02-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=200, unique=True)),
                ('employee_name', models.CharField(max_length=200, null=True)),
                ('employee_email', models.EmailField(max_length=254, null=True)),
                ('employee_mobile', models.TextField(null=True)),
                ('employee_address', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
